version: 2

before:
  hooks:
    - make build

builds:
  - id: hops
    binary: hops
    goos:
      - darwin
    goarch:
      - arm64
    skip: true

archives:
  - id: hops
    ids:
      - hops
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - hops

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: revett
    name: hops
  draft: true
