builds:
  - id: hops
    builder: bun
    binary: hops
    targets:
      - darwin-arm64
    flags:
      - --compile
      - --outfile hops
    skip: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: revett
    name: hops
  draft: true

checksum:
  name_template: "checksums.txt"
