import { writeFile } from "fs/promises";
import { getConfig } from "../utils/config";
import type { Command } from "../types/command";
import dayjs from "dayjs";

type GenerateOptions = {
  machine?: string;
};

const action: (options: GenerateOptions) => Promise<void> = async (options) => {
  if (!options.machine) {
    throw new Error("Machine flag is required");
  }
  if (options.machine === "shared") {
    throw new Error("Machine flag not allowed: shared");
  }

  const cfg = await getConfig();
  const { brewfile, machines, metadata } = cfg;

  if (!machines[options.machine]) {
    throw new Error(`Machine flag not found in hops.yml: ${options.machine}`);
  }

  if (!metadata) {
    throw new Error("Metadata not found in config");
  }

  const taps = new Set<string>();
  const formulae = new Set<string>();
  const casks = new Set<string>();

  for (const [machine, packages] of Object.entries(machines)) {
    if (machine !== options.machine && machine !== "shared") {
      continue;
    }

    packages.taps?.forEach((tap) => taps.add(tap));
    packages.formulae?.forEach((f) => formulae.add(f));
    packages.casks?.forEach((cask) => casks.add(cask));
  }

  const lines: string[] = [];

  lines.push(
    `# Generated by https://github.com/revett/hops v${metadata.version}`
  );
  lines.push(`# Config: ${metadata.path}`);
  lines.push(`# Last updated: ${dayjs().format("YYYY-MM-DD HH:mm:ss")}\n`);

  lines.push("# Taps\n");
  if (taps.size > 0) {
    [...taps].sort().forEach((tap) => lines.push(`tap "${tap}"`));
  } else {
    lines.push("# None.");
  }

  lines.push("\n# Formulae\n");
  if (formulae.size > 0) {
    [...formulae].sort().forEach((f) => lines.push(`brew "${f}"`));
  } else {
    lines.push("# None.");
  }

  lines.push("\n# Casks\n");

  if (casks.size > 0) {
    [...casks].sort().forEach((cask) => lines.push(`cask "${cask}"`));
  } else {
    lines.push("# None.");
  }

  console.log(
    `🧪 Writing ${taps.size} taps, ${formulae.size} formulae, ${casks.size} casks`
  );
  console.log(`📄 Writing Brewfile: ${brewfile}`);

  try {
    await writeFile(brewfile, lines.join("\n"), "utf8");
    console.log(`✅ Brewfile updated`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`Unable to write to Brewfile at ${brewfile}: ${msg}`);
  }
};

export const generate: Command<GenerateOptions> = {
  name: "generate",
  description: "Generate a Brewfile using hops.yml",
  options: [
    {
      flags: "--machine <machine>",
      description: "Which machine to generate the Brewfile for",
    },
  ],
  action,
};
